name: 'Last tested changes action'
description: 'Pushes last tested changes'
author: 'Miguel Andres-Martinez'
runs:
  using: 'docker'
  image: 'Dockerfile'
#outputs:
#  new_ver:
#    description: 'The new version after running bumpversion'
#  old_ver:
#    description: 'The previous version before running bumpversion'
#  part:
#    description: 'The part of version which was bumped'
#branding:
#  icon: 'chevrons-up'
#  color: 'blue'
